apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-server" .Release.Name .Values.name }}
  labels:
    app: {{ printf "%s-server" .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: {{ printf "%s-server" .Values.name }}
    release: {{ .Release.Name }}
