# Factorio image version
# ref: https://quay.io/repository/games_on_k8s/factorio?tab=tags
image: quay.io/games_on_k8s/factorio
imageTag: "0.14.22"

# Configure resource requests and limits
# ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    cpu: 10m
    memory: 32Mi

# Most of these map to environment variables. See docker-factorio for details:
# https://github.com/games-on-k8s/docker-factorio/blob/master/README.md#environment-variable-reference
factorioServer:
  name: "promfacto test"
  description: Factorio running on Kubernetes
  port: 34197
  # Lock this server down with a password.
  #password: change.me
  maxPlayers: 255
  # Publishes this server in the server browser if true.
  # You'll want to set Factorio.User below if true, as it becomes required.
  isPublic: false
  verifyIdentity: false
  # Allows or disallows console commands. Must be one of: `true`, `false`, or `admins-only`.
  allowCommands: admins-only
  # Pause the server when nobody is connected?
  noAutoPause: "false"
  # You'll want to change this to NodePort if you are on AWS.
  serviceType: NodePort

  autosave:
    # Auto-save interval in minutes.
    interval: 2
    slots: 3

  rcon:
    enabled: false
    port: 27015
    # Empty value here enables an auto-generated password.
    password: ""
    serviceType: ClusterIP

factorio:
  # Your factorio.com User/pass is needed if factorioServer.IsPublic is true.
  user:
    username: your.username
    password: your.password

  # mods:
  # - https://github.com/ncabatoff/promfacto/releases/download/0.2.0/advanced-logistics-system_0.4.0.zip
  # - https://github.com/ncabatoff/promfacto/releases/download/0.2.0/YARM_0.7.108.zip
  # - https://github.com/ncabatoff/promfacto/releases/download/0.2.0/promfacto_0.2.0.zip

persistence:
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  storageClass: default
  savedGames:
    # Set this to false if you don't care to persist saved games between restarts.
    enabled: true
    size: 1Gi
  mods:
    enabled: true
    size: 128Mi
